export const copy = {
  en: {
    identityAlt:
      "Official TRIAD symbol: luminous orbital ribbons surrounding a central star.",
    identityPrinciples: "OSCILLATION · SELF-REFERENCE · COUPLING",
    resultsEyebrow: "THE DYNAMICS, IN VIEW",
    resultsTitle: "Watch the field take form.",
    resultsIntro:
      "Fields, trajectories and structures. Follow the images into the simulations that produced them.",
    phaseEyebrow: "01 / PHASE & STRUCTURE",
    phaseTitle: "A field, seen from within.",
    phaseCopy:
      "Cyan and pink trace opposite phase windings in denser regions. Open the animation to follow the field snapshots as the camera moves around them.",
    phaseLink: "Explore the field and its animation ↗",
    phaseAlt:
      "Opposite phase windings in denser regions of a recorded 3D field.",
    contractionEyebrow: "02 / CONTRACTION & EXPANSION",
    contractionTitle: "A region contracts. Then expands.",
    contractionCopy:
      "The radius enclosing half the mass reaches its minimum at t=3.7, then expands. Follow the trajectory through density frames and measured radii.",
    contractionAlt:
      "Original density slices across the recorded contraction and expansion.",
    trajectoryLink: "Follow the trajectory ↗",
    longEyebrow: "03 / A LONGER EVOLUTION",
    longTitle: "From nested form to a filled field.",
    longCopy:
      "Follow the field through t=60: three-dimensional views, radial profiles and the later fluctuations of a finite density peak.",
    longAlt:
      "Original 3D views and time curves of the long nested-field trajectory.",
    longLink: "Explore the long record ↗",

    pageTitle: "TRIAD Universe Lab · Research, simulations and connections",
    pageDescription:
      "A living universe of research and simulations around TRIAD, Leonardo Andujar’s nonstandard quantum physics and ontology. Explore themes, original sources and recorded studies.",
    projectRules: "Read the project’s rules and methodology ↗",
    referenceRevision: "Document 1.1 ↗",
    skip: "Skip to content",
    homeLabel: "TRIAD Universe Lab home",
    languageLabel: "Language",
    triadLabel:
      "P1 oscillation, P2 self-reference and P3 coupling, acting together",
    navIdea: "The idea",
    navAtlas: "Simulations",
    navField: "Inside a field",
    heroEyebrow: "TRIAD Universe Lab · An independent, living laboratory",
    heroTitle: "A universe in motion.",
    heroIntro:
      "TRIAD is Leonardo Andujar’s nonstandard quantum physics and ontology. One immutable, indivisible equation, with all its terms acting together.",
    explore: "Explore simulations",
    meet: "Enter research ↓",
    heroCredit: "Leonardo Andujar · Nonstandard quantum physics and ontology",
    figureLabel: "FROM THE ARCHIVE / 3D FIELD",
    figureCaption:
      "Opposite phase windings, made visible. An original recorded visualization.",
    figureSource: "Follow the image to its source ↗",
    studies: "studies in Simulations",
    areas: "simulation areas",
    languages: "two ways into the same work",
    openRepo: "Open the repository ↗",
    ideaIndex: "01 / THE PROPOSITION",
    ideaTitle: "A question about\nwhat things are.",
    ideaLead: "In TRIAD, matter is an expression of a deeper dynamic.",
    readProposal: "Read the full proposal ↗",
    ideaBody:
      "TRIAD’s ontology places one immutable equation at the foundation of reality and reads the universe as simulation. The lab follows the author’s own structural and ontological methodology.",
    ideaBody2:
      "In TRIAD, self-calibration leads from chaos to dynamic equilibrium, without external calibration. Crystallization describes an organization that continues to evolve. Each study connects its declared conditions to the behavior actually recorded.",
    focus: "P1 · Oscillation",
    focusCopy: "Persistence through intrinsic oscillation.",
    memory: "P2 · Self-reference",
    memoryCopy: "Present self-interaction and memory act together.",
    bath: "P3 · Coupling",
    bathCopy:
      "Coupling throughout the system; the bath participates through dissipation and excitation.",
    whole:
      "One immutable, indivisible equation. All terms remain together throughout the evolution.",
    vocabLabel: "WORDS, IN TRIAD’S OWN SENSE",
    vocabLink: "Explore the vocabulary ↗",
    atlasIndex: "03 / SIMULATIONS · THE RECORDED WORK",
    atlasTitle: "From a question\nto its record.",
    atlasIntro:
      "Browse preserved simulation studies, historical attempts and notes. Search freely or enter through a theme from Research.",
    searchLabel: "Search simulations",
    searchPlaceholder: "Memory, structures, observation…",
    areaLabel: "Area",
    materialLabel: "Available material",
    allAreas: "All areas",
    allMaterial: "All material",
    code: "Code",
    figures: "Figures",
    data: "Data",
    notes: "Notes",
    notesOnly: "Notes only",
    reset: "Reset",
    loading: "Opening the archive…",
    availabilityNote: "Material labels describe available files.",
    emptyTitle: "No studies match this view.",
    emptyCopy: "Try a broader word or clear a filter to reopen the atlas.",
    loadMore: "Show more studies ↓",
    loadError:
      "The archive could not be loaded. Reload this page or browse the repository directly.",
    recorded: "Recorded",
    archival: "Historical record",
    openStudy: "Read study ↗",
    noFigure: "Explore the record",
    results: (shown, total) =>
      `${shown} of ${total} ${total === 1 ? "study" : "studies"}`,
    fieldIndex: "04 / INSIDE A RECORDED FIELD",
    fieldTitle: "Move through the layers.",
    fieldIntro:
      "Open two saved density volumes. Move the cutting plane and inspect the values already recorded in each state.",
    axisLabel: "Cutting axis",
    sliceLabel: "Relative position",
    scaleLabel: "Display scale",
    linear: "Linear",
    log: "Logarithmic",
    fieldNote:
      "These are final saved states from different runs. The slider moves through space, not time. Position is relative to each grid; each image uses its own density range. This viewer does not run the TRIAD equation.",
    fieldLoading: "Loading the saved volume…",
    fieldFailure: "This saved volume could not be loaded.",
    retry: "Try again",
    source: "Source data ↗",
    density: "Density |Ψ|²",
    slice: "slice",
    grid: "grid",
    inspect: "Point at a cell or focus the image and use the arrow keys.",
    canvasLabel: "Density slice. Use arrow keys to inspect neighboring cells.",
    referenceIndex: "05 / THE LAW & ITS RECORD",
    referenceTitle: "One immutable equation.\nIts documentation.",
    referenceCopy:
      "The reference document records the same equation. Follow its documentation, project rules and the methods and files behind each study.",
    equationLabel: "Equation reference document",
    equationNote: "Document revisions and preserved records",
    technicalLabel: "Simulation inspection guide",
    technicalNote: "Methods, provenance and recorded outcomes",
    runLabel: "Run or inspect a study",
    runNote: "Environments, commands and available inputs",
    authorIndex: "A LAB WITH AN AUTHOR",
    authorTitle: "An independent question.\nA shared investigation.",
    authorCopy:
      "Created by Leonardo Andujar. TRIAD Universe Lab brings the idea, the work and its history into the open — with room for new questions, simulations and languages.",
    authorLink: "Why this lab exists ↗",
    journalLink: "Read the lab journal ↗",
    contributeLink: "Contribute to the next chapter ↗",
    footerCopy: "The idea stays connected to its records.",
    wingsLabel: "Research and simulations",
    brandMain: "TRIAD",
    brandQualifier: "UNIVERSE LAB",
    navResearch: "Research",
    themes: "research themes",
    wingResearchTitle: "Research",
    wingResearchCopy:
      "Ideas, sources and connections. Follow a question across fields and see where each interpretation comes from.",
    wingSimulationTitle: "Simulations",
    wingSimulationCopy:
      "Code, conditions and recorded behavior. Open the material, inspect the figures and read the execution review.",
    wingResearchLink: "Follow the themes ↓",
    wingSimulationLink: "Explore the records ↓",
    researchIndex: "02 / RESEARCH · A THEMATIC ATLAS",
    researchTitle: "Different questions.\nConnected paths.",
    researchIntro:
      "Explore how form, memory, signals and experience connect in TRIAD. Each theme brings together readings and links to relevant simulation records.",
    researchNote:
      "A thematic connection is a reading path. The source text, the author’s interpretation and a numerical execution keep their own records.",
    researchLoading: "Opening the research themes…",
    researchEmpty: "New research themes will appear here.",
    researchError:
      "Research themes could not be loaded. Browse the research collection in the repository.",
    openTheme: "Read the theme ↗",
    relatedStudies: "Explore related studies ↓",
    noRelatedStudies: "Reading and context · no linked simulation records",
    sourceCount: (count) => `${count} ${count === 1 ? "source" : "sources"}`,
    studyCount: (count) =>
      `${count} ${count === 1 ? "linked study" : "linked studies"}`,
    researchSources: "Browse the source collection ↗",
    routesLabel: "Choose a reading path",
    routeStart: "Start with the idea",
    routeCode: "Inspect code and inputs",
    routeMethods: "Methods and provenance",
    themeLabel: "Research theme",
    allThemes: "All themes",
    auditNote:
      "Each review describes the preserved implementation and its conditions. Open it to see documented deviations, limits or missing information.",
    auditGuide: "How the execution review works ↗",
    auditReport: "Read the execution review ↗",
    auditLabels: {
      "documented-deviation": "Implementation differs",
      "not-established": "Execution not fully traceable",
      "context-only": "Context or post-processing",
      "complete-record": "Coupled terms documented",
    },
  },
  "pt-BR": {
    identityAlt:
      "Símbolo oficial TRIAD: faixas orbitais luminosas ao redor de uma estrela central.",
    identityPrinciples: "OSCILAÇÃO · AUTORREFERÊNCIA · ACOPLAMENTO",
    resultsEyebrow: "A DINÂMICA, À VISTA",
    resultsTitle: "Veja o campo ganhar forma.",
    resultsIntro:
      "Campos, trajetórias e estruturas. Acompanhe as imagens até as simulações que as produziram.",
    phaseEyebrow: "01 / FASE E ESTRUTURA",
    phaseTitle: "Um campo, visto por dentro.",
    phaseCopy:
      "Ciano e rosa mostram enrolamentos de fase em sentidos opostos nas regiões mais densas. Abra a animação para acompanhar os quadros do campo enquanto a câmera percorre a estrutura.",
    phaseLink: "Explore o campo e sua animação ↗",
    phaseAlt:
      "Enrolamentos de fase em sentidos opostos nas regiões mais densas de um campo 3D registrado.",
    contractionEyebrow: "02 / CONTRAÇÃO E EXPANSÃO",
    contractionTitle: "Uma região se contrai. Depois se expande.",
    contractionCopy:
      "O raio que contém metade da massa chega ao mínimo em t=3,7 e depois se expande. Acompanhe a trajetória pelos quadros de densidade e pelos raios medidos.",
    contractionAlt:
      "Cortes originais de densidade durante a contração e a expansão registradas.",
    trajectoryLink: "Acompanhe a trajetória ↗",
    longEyebrow: "03 / UMA EVOLUÇÃO MAIS LONGA",
    longTitle: "Da forma aninhada ao campo preenchido.",
    longCopy:
      "Siga o campo até t=60: vistas tridimensionais, perfis radiais e as flutuações posteriores de um pico de densidade finito.",
    longAlt:
      "Vistas 3D e curvas temporais originais da trajetória longa do campo aninhado.",
    longLink: "Explore o registro longo ↗",

    pageTitle: "Universo TRIAD · Pesquisa, simulações e conexões",
    pageDescription:
      "Um universo vivo de pesquisa e simulações em torno da TRIAD, a física quântica não padrão e a ontologia de Leonardo Andujar. Explore temas, fontes originais e estudos registrados.",
    projectRules: "Ler as regras e a metodologia do projeto ↗",
    referenceRevision: "Documento 1.1 ↗",
    skip: "Ir para o conteúdo",
    homeLabel: "Página inicial do Universo TRIAD",
    languageLabel: "Idioma",
    triadLabel:
      "P1 oscilação, P2 autorreferência e P3 acoplamento, agindo juntos",
    navIdea: "A ideia",
    navAtlas: "Simulações",
    navField: "Dentro do campo",
    heroEyebrow: "Universo TRIAD · Um laboratório independente e vivo",
    heroTitle: "Um universo em movimento.",
    heroIntro:
      "A TRIAD é a física quântica não padrão e a ontologia de Leonardo Andujar. Uma equação imutável e indivisível, com todos os termos atuando juntos.",
    explore: "Explorar simulações",
    meet: "Entrar na pesquisa ↓",
    heroCredit: "Leonardo Andujar · Física quântica não padrão e ontologia",
    figureLabel: "DO ACERVO / CAMPO 3D",
    figureCaption:
      "Voltas de fase em sentidos opostos, tornadas visíveis. Uma visualização original registrada.",
    figureSource: "Da imagem à sua origem ↗",
    studies: "estudos em Simulações",
    areas: "áreas de simulação",
    languages: "duas entradas para o mesmo trabalho",
    openRepo: "Abrir o repositório ↗",
    ideaIndex: "01 / A PROPOSTA",
    ideaTitle: "Uma pergunta sobre\no que as coisas são.",
    ideaLead: "Na TRIAD, a matéria é expressão de uma dinâmica mais profunda.",
    readProposal: "Ler a proposta completa ↗",
    ideaBody:
      "A ontologia da TRIAD situa uma equação imutável na base da realidade e lê o universo como simulação. O lab segue a metodologia estrutural e ontológica própria do autor.",
    ideaBody2:
      "Na TRIAD, a autocalibração conduz do caos ao equilíbrio dinâmico, sem calibração externa. A cristalização descreve uma organização que continua evoluindo. Cada estudo liga suas condições declaradas ao comportamento registrado.",
    focus: "P1 · Oscilação",
    focusCopy: "Persistência por oscilação intrínseca.",
    memory: "P2 · Autorreferência",
    memoryCopy: "Autointeração presente e memória atuam juntas.",
    bath: "P3 · Acoplamento",
    bathCopy:
      "Acoplamento por todo o sistema; o banho participa por dissipação e excitação.",
    whole:
      "Uma equação imutável e indivisível. Todos os termos permanecem juntos ao longo da evolução.",
    vocabLabel: "PALAVRAS NO SENTIDO DA TRIAD",
    vocabLink: "Explorar o vocabulário ↗",
    atlasIndex: "03 / SIMULAÇÕES · O TRABALHO REGISTRADO",
    atlasTitle: "Da pergunta\nao registro.",
    atlasIntro:
      "Explore estudos de simulação preservados, tentativas históricas e notas. Busque livremente ou entre por um tema da Pesquisa.",
    searchLabel: "Buscar simulações",
    searchPlaceholder: "Memória, estruturas, observação…",
    areaLabel: "Área",
    materialLabel: "Material disponível",
    allAreas: "Todas as áreas",
    allMaterial: "Todo o material",
    code: "Código",
    figures: "Figuras",
    data: "Dados",
    notes: "Notas",
    notesOnly: "Somente notas",
    reset: "Limpar",
    loading: "Abrindo o acervo…",
    availabilityNote: "Os rótulos de material descrevem arquivos disponíveis.",
    emptyTitle: "Nenhum estudo corresponde a esta busca.",
    emptyCopy:
      "Tente uma palavra mais ampla ou remova um filtro para reabrir o atlas.",
    loadMore: "Mostrar mais estudos ↓",
    loadError:
      "Não foi possível carregar o acervo. Atualize a página ou explore o repositório diretamente.",
    recorded: "Registrado",
    archival: "Registro histórico",
    openStudy: "Ler estudo ↗",
    noFigure: "Explorar o registro",
    results: (shown, total) =>
      `${shown} de ${total} ${total === 1 ? "estudo" : "estudos"}`,
    fieldIndex: "04 / DENTRO DE UM CAMPO REGISTRADO",
    fieldTitle: "Atravesse as camadas.",
    fieldIntro:
      "Abra dois volumes de densidade salvos. Mova o plano de corte e examine os valores já registrados em cada estado.",
    axisLabel: "Eixo do corte",
    sliceLabel: "Posição relativa",
    scaleLabel: "Escala visual",
    linear: "Linear",
    log: "Logarítmica",
    fieldNote:
      "São estados finais salvos de execuções diferentes. O controle atravessa o espaço, não o tempo. A posição é relativa a cada grade; cada imagem usa sua própria faixa de densidade. Este visualizador não executa a equação TRIAD.",
    fieldLoading: "Carregando o volume salvo…",
    fieldFailure: "Não foi possível carregar este volume.",
    retry: "Tentar novamente",
    source: "Dados de origem ↗",
    density: "Densidade |Ψ|²",
    slice: "fatia",
    grid: "grade",
    inspect: "Aponte para uma célula ou use as setas com a imagem em foco.",
    canvasLabel:
      "Fatia de densidade. Use as setas para examinar células vizinhas.",
    referenceIndex: "05 / A LEI E SEUS REGISTROS",
    referenceTitle: "Uma equação imutável.\nSua documentação.",
    referenceCopy:
      "O documento de referência registra a mesma equação. Acompanhe sua documentação, as regras do projeto e os métodos e arquivos de cada estudo.",
    equationLabel: "Documento de referência da equação",
    equationNote: "Revisões do documento e registros preservados",
    technicalLabel: "Guia de inspeção das simulações",
    technicalNote: "Métodos, proveniência e resultados registrados",
    runLabel: "Executar ou examinar um estudo",
    runNote: "Ambientes, comandos e entradas disponíveis",
    authorIndex: "UM LAB COM AUTOR",
    authorTitle: "Uma pergunta independente.\nUma investigação compartilhada.",
    authorCopy:
      "Criado por Leonardo Andujar. O Universo TRIAD abre a ideia, o trabalho e sua história — com espaço para novas perguntas, simulações e idiomas.",
    authorLink: "Por que este lab existe ↗",
    journalLink: "Ler o diário do lab ↗",
    contributeLink: "Contribuir com o próximo capítulo ↗",
    footerCopy: "A ideia continua ligada aos seus registros.",
    wingsLabel: "Pesquisa e simulações",
    brandMain: "TRIAD",
    brandQualifier: "UNIVERSO LAB",
    navResearch: "Pesquisa",
    themes: "temas de pesquisa",
    wingResearchTitle: "Pesquisa",
    wingResearchCopy:
      "Ideias, fontes e conexões. Siga uma pergunta por diferentes campos e descubra de onde vem cada interpretação.",
    wingSimulationTitle: "Simulações",
    wingSimulationCopy:
      "Código, condições e comportamento registrado. Abra o material, examine as figuras e leia a análise da execução.",
    wingResearchLink: "Seguir os temas ↓",
    wingSimulationLink: "Explorar os registros ↓",
    researchIndex: "02 / PESQUISA · UM ATLAS TEMÁTICO",
    researchTitle: "Perguntas diferentes.\nCaminhos conectados.",
    researchIntro:
      "Explore como forma, memória, sinais e experiência se conectam na TRIAD. Cada tema reúne leituras e ligações com registros de simulação relacionados.",
    researchNote:
      "Uma conexão temática é um percurso de leitura. O texto da fonte, a interpretação do autor e uma execução numérica mantêm seus próprios registros.",
    researchLoading: "Abrindo os temas de pesquisa…",
    researchEmpty: "Novos temas de pesquisa aparecerão aqui.",
    researchError:
      "Não foi possível carregar os temas. Explore a coleção de pesquisa no repositório.",
    openTheme: "Ler o tema ↗",
    relatedStudies: "Explorar estudos relacionados ↓",
    noRelatedStudies: "Leitura e contexto · sem registros de simulação ligados",
    sourceCount: (count) => `${count} ${count === 1 ? "fonte" : "fontes"}`,
    studyCount: (count) =>
      `${count} ${count === 1 ? "estudo ligado" : "estudos ligados"}`,
    researchSources: "Explorar a coleção de fontes ↗",
    routesLabel: "Escolha um percurso de leitura",
    routeStart: "Começar pela ideia",
    routeCode: "Examinar código e entradas",
    routeMethods: "Métodos e proveniência",
    themeLabel: "Tema de pesquisa",
    allThemes: "Todos os temas",
    auditNote:
      "Cada análise descreve a implementação preservada e suas condições. Abra para ver desvios documentados, limites ou informações ausentes.",
    auditGuide: "Como funciona a análise das execuções ↗",
    auditReport: "Ler a análise da execução ↗",
    auditLabels: {
      "documented-deviation": "Implementação divergente",
      "not-established": "Execução sem rastreabilidade completa",
      "context-only": "Contexto ou pós-processamento",
      "complete-record": "Termos conjuntos documentados",
    },
  },
};
export const concepts = {
  en: [
    [
      "Atom",
      "A Gaussian packet is one atom in TRIAD’s operational vocabulary. The ontological reading treats matter as forms of the same underlying dynamics, including structures nested within larger structures.",
    ],
    [
      "P2 · Self-reference",
      "P2 includes present self-interaction and the memory of earlier states. The auxiliary fields carry density history on several time scales, and their weighted sum acts back on the present.",
    ],
    [
      "Sound & light",
      "In TRIAD’s ontological vocabulary, vibration, friction, frequency (sound) and energy (light) form a conceptual sequence. Each numerical record identifies the quantity that its plot or signal actually shows.",
    ],
    [
      "Universe",
      "TRIAD’s ontology places its immutable equation at the deepest layer of reality and reads the universe as simulation. The lab explores this through documented simulations and their recorded outcomes.",
    ],
  ],
  "pt-BR": [
    [
      "Átomo",
      "Um pacote gaussiano é um átomo no vocabulário operacional da TRIAD. A leitura ontológica trata a matéria como formas da mesma dinâmica fundamental, incluindo estruturas dentro de estruturas maiores.",
    ],
    [
      "P2 · Autorreferência",
      "P2 inclui a autointeração presente e a memória de estados anteriores. Os campos auxiliares carregam a história da densidade em diferentes escalas de tempo, e sua soma ponderada volta a agir sobre o presente.",
    ],
    [
      "Som e luz",
      "No vocabulário ontológico da TRIAD, vibração, atrito, frequência (som) e energia (luz) formam uma sequência conceitual. Cada registro numérico identifica a grandeza que sua figura ou seu sinal mostra.",
    ],
    [
      "Universo",
      "A ontologia da TRIAD situa sua equação imutável na camada mais profunda da realidade e lê o universo como simulação. O lab explora isso por simulações documentadas e seus resultados registrados.",
    ],
  ],
};
