export const copy = {
  en: {
    skip: "Skip to content",
    homeLabel: "TRIAD Lab home",
    languageLabel: "Language",
    triadLabel: "Focus, memory and bath acting together",
    navIdea: "The idea",
    navAtlas: "The atlas",
    navField: "Inside a field",
    heroEyebrow: "An independent, living laboratory",
    heroTitle: "What if one equation underlies reality?",
    heroIntro:
      "TRIAD explores a hypothesis about the deepest layer of the universe — through focus, memory and bath acting together.",
    explore: "Explore the studies",
    meet: "Meet the idea ↓",
    heroCredit: "A proposal by Leonardo Andujar · Nonstandard quantum physics",
    figureLabel: "FROM THE ARCHIVE / 3D FIELD",
    figureCaption:
      "Opposite phase windings, made visible. An original recorded visualization.",
    figureSource: "Follow the image to its source ↗",
    studies: "studies to explore",
    areas: "connected areas",
    languages: "two ways into the same work",
    openRepo: "Open the repository ↗",
    ideaIndex: "01 / THE PROPOSITION",
    ideaTitle: "A question about\nwhat things are.",
    ideaLead: "What we call matter may be an expression of a deeper dynamic.",
    readProposal: "Read the full proposal ↗",
    ideaBody:
      "TRIAD is Leonardo Andujar’s ontological proposal: an investigation into whether one fundamental equation could underlie the universe, including the hypothesis that reality is a simulation.",
    ideaBody2:
      "The laboratory makes that exploration inspectable. The author’s interpretation, the numerical implementation and the recorded outcome each have a place.",
    focus: "Focus",
    focusCopy: "Concentration within the field.",
    memory: "Memory",
    memoryCopy: "A history that acts back.",
    bath: "Bath",
    bathCopy: "Excitation and dissipation in the same dynamics.",
    whole:
      "One complete system. The current reference keeps the equation’s terms together.",
    vocabLabel: "WORDS, IN TRIAD’S OWN SENSE",
    vocabLink: "Explore the vocabulary ↗",
    atlasIndex: "02 / THE EXPERIMENT ATLAS",
    atlasTitle: "Follow your curiosity.",
    atlasIntro:
      "A growing collection of questions, attempts and recorded outcomes. Choose an area or find a thread to follow.",
    searchLabel: "Search the lab",
    searchPlaceholder: "Memory, structures, observation…",
    areaLabel: "Area",
    materialLabel: "Available material",
    allAreas: "All areas",
    allMaterial: "All material",
    code: "Code",
    figures: "Figures",
    data: "Data",
    notes: "Notes",
    notesOnly: "Notes only",
    reset: "Reset",
    loading: "Opening the archive…",
    availabilityNote: "Material availability, not a verdict on the hypothesis.",
    emptyTitle: "No studies match this view.",
    emptyCopy: "Try a broader word or clear a filter to reopen the atlas.",
    loadMore: "Show more studies ↓",
    loadError:
      "The archive could not be loaded. Reload this page or browse the repository directly.",
    recorded: "Recorded",
    archival: "Historical record",
    openStudy: "Read study ↗",
    noFigure: "Explore the record",
    results: (shown, total) => `${shown} of ${total} studies`,
    fieldIndex: "03 / INSIDE A RECORDED FIELD",
    fieldTitle: "Move through the layers.",
    fieldIntro:
      "Open two saved density volumes. Move the cutting plane and inspect the values already recorded in each state.",
    axisLabel: "Cutting axis",
    sliceLabel: "Relative position",
    scaleLabel: "Display scale",
    linear: "Linear",
    log: "Logarithmic",
    fieldNote:
      "These are final saved states from different runs. The slider moves through space, not time. Position is relative to each grid; each image uses its own density range. This viewer does not run the TRIAD equation.",
    fieldLoading: "Loading the saved volume…",
    fieldFailure: "This saved volume could not be loaded.",
    retry: "Try again",
    source: "Source data ↗",
    density: "Density |Ψ|²",
    slice: "slice",
    grid: "grid",
    inspect: "Point at a cell or focus the image and use the arrow keys.",
    canvasLabel: "Density slice. Use arrow keys to inspect neighboring cells.",
    referenceIndex: "04 / THE LAW & ITS RECORD",
    referenceTitle: "The complete equation.\nAn accessible record.",
    referenceCopy:
      "Go from the proposal to the mathematical specification, then to the methods and files behind each study.",
    equationLabel: "Equation reference",
    equationNote: "Current edition + preserved version history",
    technicalLabel: "Research guide",
    technicalNote: "Methods, provenance and recorded outcomes",
    runLabel: "Run or inspect a study",
    runNote: "Environments, commands and available inputs",
    authorIndex: "A LAB WITH AN AUTHOR",
    authorTitle: "An independent question.\nA shared investigation.",
    authorCopy:
      "Created by Leonardo Andujar. TRIAD Lab brings the idea, the work and its history into the open — with room for new questions, experiments and languages.",
    authorLink: "Why this lab exists ↗",
    journalLink: "Read the lab journal ↗",
    contributeLink: "Contribute to the next chapter ↗",
    footerCopy: "The idea stays connected to its records.",
  },
  "pt-BR": {
    skip: "Ir para o conteúdo",
    homeLabel: "Página inicial do TRIAD Lab",
    languageLabel: "Idioma",
    triadLabel: "Foco, memória e banho agindo juntos",
    navIdea: "A ideia",
    navAtlas: "O atlas",
    navField: "Dentro do campo",
    heroEyebrow: "Um laboratório independente e vivo",
    heroTitle: "E se uma equação fosse a base da realidade?",
    heroIntro:
      "A TRIAD explora uma hipótese sobre a camada mais profunda do universo — pela ação conjunta de foco, memória e banho.",
    explore: "Explorar os estudos",
    meet: "Conhecer a ideia ↓",
    heroCredit: "Uma proposta de Leonardo Andujar · Física quântica não padrão",
    figureLabel: "DO ACERVO / CAMPO 3D",
    figureCaption:
      "Voltas de fase em sentidos opostos, tornadas visíveis. Uma visualização original registrada.",
    figureSource: "Da imagem à sua origem ↗",
    studies: "estudos para explorar",
    areas: "áreas conectadas",
    languages: "duas entradas para o mesmo trabalho",
    openRepo: "Abrir o repositório ↗",
    ideaIndex: "01 / A PROPOSTA",
    ideaTitle: "Uma pergunta sobre\no que as coisas são.",
    ideaLead:
      "O que chamamos de matéria pode ser a expressão de uma dinâmica mais profunda.",
    readProposal: "Ler a proposta completa ↗",
    ideaBody:
      "A TRIAD é a proposta ontológica de Leonardo Andujar: uma investigação sobre a possibilidade de uma equação fundamental estar na base do universo, incluindo a hipótese de que a realidade seja uma simulação.",
    ideaBody2:
      "O laboratório permite acompanhar essa exploração. A interpretação do autor, a implementação numérica e o resultado registrado têm seu lugar.",
    focus: "Foco",
    focusCopy: "Concentração dentro do campo.",
    memory: "Memória",
    memoryCopy: "Uma história que age de volta.",
    bath: "Banho",
    bathCopy: "Excitação e dissipação na mesma dinâmica.",
    whole:
      "Um sistema completo. A referência vigente mantém os termos da equação juntos.",
    vocabLabel: "PALAVRAS NO SENTIDO DA TRIAD",
    vocabLink: "Explorar o vocabulário ↗",
    atlasIndex: "02 / O ATLAS DE EXPERIMENTOS",
    atlasTitle: "Siga sua curiosidade.",
    atlasIntro:
      "Uma coleção crescente de perguntas, tentativas e resultados registrados. Escolha uma área ou encontre um fio para seguir.",
    searchLabel: "Buscar no lab",
    searchPlaceholder: "Memória, estruturas, observação…",
    areaLabel: "Área",
    materialLabel: "Material disponível",
    allAreas: "Todas as áreas",
    allMaterial: "Todo o material",
    code: "Código",
    figures: "Figuras",
    data: "Dados",
    notes: "Notas",
    notesOnly: "Somente notas",
    reset: "Limpar",
    loading: "Abrindo o acervo…",
    availabilityNote:
      "Disponibilidade de material, não um veredito sobre a hipótese.",
    emptyTitle: "Nenhum estudo corresponde a esta busca.",
    emptyCopy:
      "Tente uma palavra mais ampla ou remova um filtro para reabrir o atlas.",
    loadMore: "Mostrar mais estudos ↓",
    loadError:
      "Não foi possível carregar o acervo. Atualize a página ou explore o repositório diretamente.",
    recorded: "Registrado",
    archival: "Registro histórico",
    openStudy: "Ler estudo ↗",
    noFigure: "Explorar o registro",
    results: (shown, total) => `${shown} de ${total} estudos`,
    fieldIndex: "03 / DENTRO DE UM CAMPO REGISTRADO",
    fieldTitle: "Atravesse as camadas.",
    fieldIntro:
      "Abra dois volumes de densidade salvos. Mova o plano de corte e examine os valores já registrados em cada estado.",
    axisLabel: "Eixo do corte",
    sliceLabel: "Posição relativa",
    scaleLabel: "Escala visual",
    linear: "Linear",
    log: "Logarítmica",
    fieldNote:
      "São estados finais salvos de execuções diferentes. O controle atravessa o espaço, não o tempo. A posição é relativa a cada grade; cada imagem usa sua própria faixa de densidade. Este visualizador não executa a equação TRIAD.",
    fieldLoading: "Carregando o volume salvo…",
    fieldFailure: "Não foi possível carregar este volume.",
    retry: "Tentar novamente",
    source: "Dados de origem ↗",
    density: "Densidade |Ψ|²",
    slice: "fatia",
    grid: "grade",
    inspect: "Aponte para uma célula ou use as setas com a imagem em foco.",
    canvasLabel:
      "Fatia de densidade. Use as setas para examinar células vizinhas.",
    referenceIndex: "04 / A LEI E SEUS REGISTROS",
    referenceTitle: "A equação completa.\nUm registro acessível.",
    referenceCopy:
      "Da proposta à especificação matemática, seguindo até os métodos e arquivos de cada estudo.",
    equationLabel: "Referência da equação",
    equationNote: "Edição vigente e histórico preservado",
    technicalLabel: "Guia técnico",
    technicalNote: "Métodos, proveniência e resultados registrados",
    runLabel: "Executar ou examinar um estudo",
    runNote: "Ambientes, comandos e entradas disponíveis",
    authorIndex: "UM LAB COM AUTOR",
    authorTitle: "Uma pergunta independente.\nUma investigação compartilhada.",
    authorCopy:
      "Criado por Leonardo Andujar. O TRIAD Lab abre a ideia, o trabalho e sua história — com espaço para novas perguntas, experimentos e idiomas.",
    authorLink: "Por que este lab existe ↗",
    journalLink: "Ler o diário do lab ↗",
    contributeLink: "Contribuir com o próximo capítulo ↗",
    footerCopy: "A ideia continua ligada aos seus registros.",
  },
};
export const concepts = {
  en: [
    [
      "Atom",
      "In the author’s operational vocabulary, a Gaussian seed is read as an atom. The wider proposal treats what we call matter as dynamics; this use of “atom” belongs to TRIAD’s own account.",
    ],
    [
      "Memory",
      "Auxiliary fields respond to density over several time scales. The history they carry acts back on the field. Its direction depends on the declared coupling signs.",
    ],
    [
      "Sound & light",
      "The author proposes a conceptual path from vibrating atoms through friction and frequency (sound) to energy (light). This is a reading to explore; it is not a mathematical equivalence supplied by the reference.",
    ],
    [
      "Universe",
      "TRIAD asks whether a common underlying dynamics could account for reality, including the hypothesis that we live in a simulation. A simulated volume is a place to explore that proposal.",
    ],
  ],
  "pt-BR": [
    [
      "Átomo",
      "No vocabulário operacional do autor, uma semente gaussiana é lida como um átomo. A proposta mais ampla trata o que chamamos de matéria como dinâmica; esse uso de “átomo” pertence à leitura própria da TRIAD.",
    ],
    [
      "Memória",
      "Campos auxiliares respondem à densidade em diferentes escalas de tempo. A história que carregam volta a agir sobre o campo. O sentido dessa ação depende dos sinais de acoplamento declarados.",
    ],
    [
      "Som e luz",
      "O autor propõe um percurso conceitual de átomos vibrando, passando por atrito e frequência (som), até energia (luz). É uma leitura a explorar; não uma equivalência matemática fornecida pela referência.",
    ],
    [
      "Universo",
      "A TRIAD pergunta se uma dinâmica fundamental comum poderia explicar a realidade, incluindo a hipótese de vivermos em uma simulação. Um volume simulado é um lugar para explorar essa proposta.",
    ],
  ],
};
