export const copy = {
  en: {
    pageTitle: "TRIAD Lab · Nonstandard physics and ontology",
    pageDescription:
      "Explore TRIAD: nonstandard quantum physics and ontology through one immutable, indivisible equation, original records and a living experiment atlas.",
    projectRules: "Read the project’s rules and methodology ↗",
    referenceRevision: "Document 1.1 ↗",
    skip: "Skip to content",
    homeLabel: "TRIAD Lab home",
    languageLabel: "Language",
    triadLabel:
      "P1 oscillation, P2 self-reference and P3 coupling, acting together",
    navIdea: "The idea",
    navAtlas: "The atlas",
    navField: "Inside a field",
    heroEyebrow: "An independent, living laboratory",
    heroTitle: "What if one equation underlies reality?",
    heroIntro:
      "TRIAD is Leonardo Andujar’s nonstandard quantum physics and ontology. One immutable, indivisible equation, with all its terms acting together.",
    explore: "Explore the studies",
    meet: "Meet the idea ↓",
    heroCredit: "Leonardo Andujar · Nonstandard quantum physics and ontology",
    figureLabel: "FROM THE ARCHIVE / 3D FIELD",
    figureCaption:
      "Opposite phase windings, made visible. An original recorded visualization.",
    figureSource: "Follow the image to its source ↗",
    studies: "studies to explore",
    areas: "connected areas",
    languages: "two ways into the same work",
    openRepo: "Open the repository ↗",
    ideaIndex: "01 / THE PROPOSITION",
    ideaTitle: "A question about\nwhat things are.",
    ideaLead: "What we call matter may be an expression of a deeper dynamic.",
    readProposal: "Read the full proposal ↗",
    ideaBody:
      "The central hypothesis of TRIAD places one immutable equation at the deepest layer of the universe, including the hypothesis that reality is a simulation. The lab follows the author’s own structural and ontological methodology.",
    ideaBody2:
      "In TRIAD, self-calibration leads from chaos to dynamic equilibrium, without external calibration. Crystallization describes an organization that continues to evolve. Each study connects its declared conditions to the behavior actually recorded.",
    focus: "P1 · Oscillation",
    focusCopy: "Persistence through intrinsic oscillation.",
    memory: "P2 · Self-reference",
    memoryCopy: "Present self-interaction and memory act together.",
    bath: "P3 · Coupling",
    bathCopy: "Continuous coupling through dissipation and excitation.",
    whole:
      "One immutable, indivisible equation. All terms remain together throughout the evolution.",
    vocabLabel: "WORDS, IN TRIAD’S OWN SENSE",
    vocabLink: "Explore the vocabulary ↗",
    atlasIndex: "02 / THE EXPERIMENT ATLAS",
    atlasTitle: "Follow your curiosity.",
    atlasIntro:
      "A growing collection of questions, attempts and recorded outcomes. Choose an area or find a thread to follow.",
    searchLabel: "Search the lab",
    searchPlaceholder: "Memory, structures, observation…",
    areaLabel: "Area",
    materialLabel: "Available material",
    allAreas: "All areas",
    allMaterial: "All material",
    code: "Code",
    figures: "Figures",
    data: "Data",
    notes: "Notes",
    notesOnly: "Notes only",
    reset: "Reset",
    loading: "Opening the archive…",
    availabilityNote: "Labels show which materials are available.",
    emptyTitle: "No studies match this view.",
    emptyCopy: "Try a broader word or clear a filter to reopen the atlas.",
    loadMore: "Show more studies ↓",
    loadError:
      "The archive could not be loaded. Reload this page or browse the repository directly.",
    recorded: "Recorded",
    archival: "Historical record",
    openStudy: "Read study ↗",
    noFigure: "Explore the record",
    results: (shown, total) => `${shown} of ${total} studies`,
    fieldIndex: "03 / INSIDE A RECORDED FIELD",
    fieldTitle: "Move through the layers.",
    fieldIntro:
      "Open two saved density volumes. Move the cutting plane and inspect the values already recorded in each state.",
    axisLabel: "Cutting axis",
    sliceLabel: "Relative position",
    scaleLabel: "Display scale",
    linear: "Linear",
    log: "Logarithmic",
    fieldNote:
      "These are final saved states from different runs. The slider moves through space, not time. Position is relative to each grid; each image uses its own density range. This viewer does not run the TRIAD equation.",
    fieldLoading: "Loading the saved volume…",
    fieldFailure: "This saved volume could not be loaded.",
    retry: "Try again",
    source: "Source data ↗",
    density: "Density |Ψ|²",
    slice: "slice",
    grid: "grid",
    inspect: "Point at a cell or focus the image and use the arrow keys.",
    canvasLabel: "Density slice. Use arrow keys to inspect neighboring cells.",
    referenceIndex: "04 / THE LAW & ITS RECORD",
    referenceTitle: "One immutable equation.\nIts documentation.",
    referenceCopy:
      "The reference document records the same equation. Follow its documentation, project rules and the methods and files behind each study.",
    equationLabel: "Equation reference document",
    equationNote: "Document revisions and preserved records",
    technicalLabel: "Research guide",
    technicalNote: "Methods, provenance and recorded outcomes",
    runLabel: "Run or inspect a study",
    runNote: "Environments, commands and available inputs",
    authorIndex: "A LAB WITH AN AUTHOR",
    authorTitle: "An independent question.\nA shared investigation.",
    authorCopy:
      "Created by Leonardo Andujar. TRIAD Lab brings the idea, the work and its history into the open — with room for new questions, experiments and languages.",
    authorLink: "Why this lab exists ↗",
    journalLink: "Read the lab journal ↗",
    contributeLink: "Contribute to the next chapter ↗",
    footerCopy: "The idea stays connected to its records.",
  },
  "pt-BR": {
    pageTitle: "TRIAD Lab · Física não padrão e ontologia",
    pageDescription:
      "Explore a TRIAD: física quântica não padrão e ontologia por uma equação imutável e indivisível, registros originais e um atlas vivo de experimentos.",
    projectRules: "Ler as regras e a metodologia do projeto ↗",
    referenceRevision: "Documento 1.1 ↗",
    skip: "Ir para o conteúdo",
    homeLabel: "Página inicial do TRIAD Lab",
    languageLabel: "Idioma",
    triadLabel:
      "P1 oscilação, P2 autorreferência e P3 acoplamento, agindo juntos",
    navIdea: "A ideia",
    navAtlas: "O atlas",
    navField: "Dentro do campo",
    heroEyebrow: "Um laboratório independente e vivo",
    heroTitle: "E se uma equação fosse a base da realidade?",
    heroIntro:
      "A TRIAD é a física quântica não padrão e a ontologia de Leonardo Andujar. Uma equação imutável e indivisível, com todos os termos atuando juntos.",
    explore: "Explorar os estudos",
    meet: "Conhecer a ideia ↓",
    heroCredit: "Leonardo Andujar · Física quântica não padrão e ontologia",
    figureLabel: "DO ACERVO / CAMPO 3D",
    figureCaption:
      "Voltas de fase em sentidos opostos, tornadas visíveis. Uma visualização original registrada.",
    figureSource: "Da imagem à sua origem ↗",
    studies: "estudos para explorar",
    areas: "áreas conectadas",
    languages: "duas entradas para o mesmo trabalho",
    openRepo: "Abrir o repositório ↗",
    ideaIndex: "01 / A PROPOSTA",
    ideaTitle: "Uma pergunta sobre\no que as coisas são.",
    ideaLead:
      "O que chamamos de matéria pode ser a expressão de uma dinâmica mais profunda.",
    readProposal: "Ler a proposta completa ↗",
    ideaBody:
      "A hipótese central da TRIAD situa uma equação imutável na camada mais profunda do universo, incluindo a hipótese de que a realidade seja uma simulação. O lab segue a metodologia estrutural e ontológica própria do autor.",
    ideaBody2:
      "Na TRIAD, a autocalibração conduz do caos ao equilíbrio dinâmico, sem calibração externa. A cristalização descreve uma organização que continua evoluindo. Cada estudo liga suas condições declaradas ao comportamento registrado.",
    focus: "P1 · Oscilação",
    focusCopy: "Persistência por oscilação intrínseca.",
    memory: "P2 · Autorreferência",
    memoryCopy: "Autointeração presente e memória atuam juntas.",
    bath: "P3 · Acoplamento",
    bathCopy: "Acoplamento contínuo por dissipação e excitação.",
    whole:
      "Uma equação imutável e indivisível. Todos os termos permanecem juntos ao longo da evolução.",
    vocabLabel: "PALAVRAS NO SENTIDO DA TRIAD",
    vocabLink: "Explorar o vocabulário ↗",
    atlasIndex: "02 / O ATLAS DE EXPERIMENTOS",
    atlasTitle: "Siga sua curiosidade.",
    atlasIntro:
      "Uma coleção crescente de perguntas, tentativas e resultados registrados. Escolha uma área ou encontre um fio para seguir.",
    searchLabel: "Buscar no lab",
    searchPlaceholder: "Memória, estruturas, observação…",
    areaLabel: "Área",
    materialLabel: "Material disponível",
    allAreas: "Todas as áreas",
    allMaterial: "Todo o material",
    code: "Código",
    figures: "Figuras",
    data: "Dados",
    notes: "Notas",
    notesOnly: "Somente notas",
    reset: "Limpar",
    loading: "Abrindo o acervo…",
    availabilityNote: "Os rótulos indicam quais materiais estão disponíveis.",
    emptyTitle: "Nenhum estudo corresponde a esta busca.",
    emptyCopy:
      "Tente uma palavra mais ampla ou remova um filtro para reabrir o atlas.",
    loadMore: "Mostrar mais estudos ↓",
    loadError:
      "Não foi possível carregar o acervo. Atualize a página ou explore o repositório diretamente.",
    recorded: "Registrado",
    archival: "Registro histórico",
    openStudy: "Ler estudo ↗",
    noFigure: "Explorar o registro",
    results: (shown, total) => `${shown} de ${total} estudos`,
    fieldIndex: "03 / DENTRO DE UM CAMPO REGISTRADO",
    fieldTitle: "Atravesse as camadas.",
    fieldIntro:
      "Abra dois volumes de densidade salvos. Mova o plano de corte e examine os valores já registrados em cada estado.",
    axisLabel: "Eixo do corte",
    sliceLabel: "Posição relativa",
    scaleLabel: "Escala visual",
    linear: "Linear",
    log: "Logarítmica",
    fieldNote:
      "São estados finais salvos de execuções diferentes. O controle atravessa o espaço, não o tempo. A posição é relativa a cada grade; cada imagem usa sua própria faixa de densidade. Este visualizador não executa a equação TRIAD.",
    fieldLoading: "Carregando o volume salvo…",
    fieldFailure: "Não foi possível carregar este volume.",
    retry: "Tentar novamente",
    source: "Dados de origem ↗",
    density: "Densidade |Ψ|²",
    slice: "fatia",
    grid: "grade",
    inspect: "Aponte para uma célula ou use as setas com a imagem em foco.",
    canvasLabel:
      "Fatia de densidade. Use as setas para examinar células vizinhas.",
    referenceIndex: "04 / A LEI E SEUS REGISTROS",
    referenceTitle: "Uma equação imutável.\nSua documentação.",
    referenceCopy:
      "O documento de referência registra a mesma equação. Acompanhe sua documentação, as regras do projeto e os métodos e arquivos de cada estudo.",
    equationLabel: "Documento de referência da equação",
    equationNote: "Revisões do documento e registros preservados",
    technicalLabel: "Guia técnico",
    technicalNote: "Métodos, proveniência e resultados registrados",
    runLabel: "Executar ou examinar um estudo",
    runNote: "Ambientes, comandos e entradas disponíveis",
    authorIndex: "UM LAB COM AUTOR",
    authorTitle: "Uma pergunta independente.\nUma investigação compartilhada.",
    authorCopy:
      "Criado por Leonardo Andujar. O TRIAD Lab abre a ideia, o trabalho e sua história — com espaço para novas perguntas, experimentos e idiomas.",
    authorLink: "Por que este lab existe ↗",
    journalLink: "Ler o diário do lab ↗",
    contributeLink: "Contribuir com o próximo capítulo ↗",
    footerCopy: "A ideia continua ligada aos seus registros.",
  },
};
export const concepts = {
  en: [
    [
      "Atom",
      "A Gaussian packet is one atom in TRIAD’s operational vocabulary. The ontological reading treats matter as forms of the same underlying dynamics, including structures nested within larger structures.",
    ],
    [
      "P2 · Self-reference",
      "P2 includes present self-interaction and the memory of earlier states. The auxiliary fields carry density history on several time scales, and their weighted sum acts back on the present.",
    ],
    [
      "Sound & light",
      "In TRIAD’s ontological vocabulary, vibration, friction, frequency (sound) and energy (light) form a conceptual sequence. Each numerical record identifies the quantity that its plot or signal actually shows.",
    ],
    [
      "Universe",
      "The central hypothesis places the immutable equation at the deepest layer of reality, including the possibility that we live in a simulation. The lab explores this through documented simulations and their recorded outcomes.",
    ],
  ],
  "pt-BR": [
    [
      "Átomo",
      "Um pacote gaussiano é um átomo no vocabulário operacional da TRIAD. A leitura ontológica trata a matéria como formas da mesma dinâmica fundamental, incluindo estruturas dentro de estruturas maiores.",
    ],
    [
      "P2 · Autorreferência",
      "P2 inclui a autointeração presente e a memória de estados anteriores. Os campos auxiliares carregam a história da densidade em diferentes escalas de tempo, e sua soma ponderada volta a agir sobre o presente.",
    ],
    [
      "Som e luz",
      "No vocabulário ontológico da TRIAD, vibração, atrito, frequência (som) e energia (luz) formam uma sequência conceitual. Cada registro numérico identifica a grandeza que sua figura ou seu sinal mostra.",
    ],
    [
      "Universo",
      "A hipótese central situa a equação imutável na camada mais profunda da realidade, incluindo a possibilidade de vivermos em uma simulação. O lab explora isso por simulações documentadas e seus resultados registrados.",
    ],
  ],
};
